version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population_smr:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2021-02-01 by month" --output-dir=output/measures
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv

  generate_study_population_hospital_admission:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hospital_admission --index-date-range "2019-01-01 to 2021-02-01 by month" --output-dir=output/measures
    outputs:
      highly_sensitive:
        cohort: output/measures/input_hospital_admission*.csv
  
  generate_measures_smr:
      run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output/measures
      needs: [generate_study_population_smr]
      outputs:
        moderately_sensitive:
          measure_csv: output/measures/measure_*.csv

  generate_measures_hospital_admission:
      run: cohortextractor:latest generate_measures --study-definition study_definition_hospital_admission --output-dir=output/measures
      needs: [generate_study_population_hospital_admission]
      outputs:
        moderately_sensitive:
          measure_csv: output/measures/measure_smr_by_hospital_admission*.csv
  
  generate_plots_smr:
    run: python:latest python analysis/generate_plots_smr.py
    needs: [generate_measures_smr]
    outputs:
      moderately_sensitive:
        figure1: output/figures/population_rates.jpeg
        figure2: output/figures/sex_rates.jpeg
        figure3: output/figures/region_rates.jpeg
        figure4: output/figures/age_rates.jpeg
        figure5: output/figures/hosp_adm_rates.jpeg
        figure6: output/figures/care_home_status_rates.jpeg
        figure7: output/figures/falls_rates.jpeg

